CREATE DATABASE IF NOT EXISTS SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(70)
);


CREATE TABLE COURSE(
ID INT PRIMARY KEY,
NAME VARCHAR(70)
);

INSERT INTO STUDENT
(ID,NAME)
VALUES
(101,"GAFRU"),
(102,"SANJEEDA"),
(103,"SYED");


INSERT INTO COURSE
 (ID, NAME) 
VALUES
(101, "Mathematics"),
(102, "Physics"),
(103, "Chemistry"),
(104, "Biology"),
(105, "Computer Science"),
(106, "English");

SELECT * FROM STUDENT;
SELECT *FROM COURSE;
-- inner join
SELECT *
FROM STUDENT AS S
INNER JOIN COURSE AS C
ON S.ID=C.ID;
-- left join
SELECT *
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID=C.ID;

-- right join
SELECT *
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID=C.ID;

-- full join
SELECT *
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID=C.ID
UNION
SELECT *
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID=C.ID;

-- exculisive left join
SELECT *
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID=C.ID
WHERE C.ID IS NULL;

-- exculsive right join
SELECT *
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID=C.ID
WHERE S.ID IS NULL;
